[package]
name = "darwincodesign"
version = "0.1.0"
authors = ["Ted Mielczarek <ted@mielczarek.org>"]

[dependencies]
clap = "2.25.0"
env_logger = "0.4.3"
error-chain = "0.9.0"
hex = "0.2.0"
log = "0.3.8"
mach_o_sys = "0.1.1"
macho = "0.4.1"
memmap = "0.5.2"
nom = "3.1.0"
ring = "0.9.0"
